package com.armyknife.tools.core.designsystem

import androidx.compose.ui.graphics.Color

// Light Theme
val md_theme_light_primary = Color(0xFF006A68)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF7DF5F2)
val md_theme_light_onPrimaryContainer = Color(0xFF00201F)
val md_theme_light_secondary = Color(0xFF4A6362)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCCE8E6)
val md_theme_light_onSecondaryContainer = Color(0xFF061F1F)
val md_theme_light_tertiary = Color(0xFF4A607B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD1E4FF)
val md_theme_light_onTertiaryContainer = Color(0xFF021D34)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFCFB)
val md_theme_light_onBackground = Color(0xFF191C1C)
val md_theme_light_surface = Color(0xFFFBFCFB)
val md_theme_light_onSurface = Color(0xFF191C1C)
val md_theme_light_surfaceVariant = Color(0xFFDAE5E3)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4948)
val md_theme_light_outline = Color(0xFF6F7978)
val md_theme_light_outlineVariant = Color(0xFFBEC9C7)

// Dark Theme
val md_theme_dark_primary = Color(0xFF5DDDDA)
val md_theme_dark_onPrimary = Color(0xFF003736)
val md_theme_dark_primaryContainer = Color(0xFF00504E)
val md_theme_dark_onPrimaryContainer = Color(0xFF7DF5F2)
val md_theme_dark_secondary = Color(0xFFB0CCC9)
val md_theme_dark_onSecondary = Color(0xFF1B3433)
val md_theme_dark_secondaryContainer = Color(0xFF334B4A)
val md_theme_dark_onSecondaryContainer = Color(0xFFCCE8E6)
val md_theme_dark_tertiary = Color(0xFFB1C8E8)
val md_theme_dark_onTertiary = Color(0xFF1B324B)
val md_theme_dark_tertiaryContainer = Color(0xFF324963)
val md_theme_dark_onTertiaryContainer = Color(0xFFD1E4FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1C)
val md_theme_dark_onBackground = Color(0xFFE1E3E2)
val md_theme_dark_surface = Color(0xFF191C1C)
val md_theme_dark_onSurface = Color(0xFFE1E3E2)
val md_theme_dark_surfaceVariant = Color(0xFF3F4948)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC9C7)
val md_theme_dark_outline = Color(0xFF889392)
val md_theme_dark_outlineVariant = Color(0xFF3F4948)
